# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adfb918342795a1a909e6c5201cd93cf7b9da680a48ac6227b85228a309af96bf2f8f1788a3129588711f99f2b6ad702fb8a3d93995b9bcbccc1f31db2e0fac5

test:
  secret_key_base: 7219d8adffbae2a5e3861abe4ff1ae39dcbd9e99f0e6f0f2d29ff28d6e8ef09b48e0989926554f7f42b14265ff845648587dc1a2025552d5eb170ab7e23a2a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
